### ISSUE TITLE
Gnome terminal with systemd dbus

### ISSUE THREAD

**Issue by justin-gerhardt** [nix-community/home-manager#1234]
The systemwide gnome terminal module installs a systemd user unit for the gnome-terminal-server. https://github.com/NixOS/nixpkgs/blob/6eae9e0861d117b82a4231a8fa0d35e306840cab/nixos/modules/programs/gnome-terminal.nix#L33
as well as a dbus file.

The home-manager version doesn't (and I can find no analoge for systemd.packages and services.dbus.packages in the home-manager options). 

Normally this isn't a problem. By default all xsessions launch a dbus daemon early in startup that allows gnome terminal to start. I've had to replace this with the systemd launched dbus daemon to avoid a few race conditions. As a result gnome terminal will crash on boot with "# Error creating terminal: Unit gnome-terminal-server.service not found."

Ideally, a user version of systemd.packages and services.dbus.packages would be added. Failing that adding the following service with the name "gnome-terminal-server" as well as installing the config from ${pkgs.gnome3.gnome-terminal}/share/dbus-1/services/org.gnome.Terminal.service would produce a working application (subject to upstream changes).

```
[Unit]
Description=GNOME Terminal Server
PartOf=graphical-session.target
[Service]
Slice=apps-org.gnome.Terminal.slice
Type=dbus
BusName=org.gnome.Terminal
ExecStart=${pkgs.gnome3.gnome-terminal}/libexec/gnome-terminal-server
TimeoutStopSec=5s
KillMode=process
```

**Comment by rycee** [comment]
Glad somebody else has started looking at this! Please have a look at https://github.com/NixOS/nixpkgs/issues/17943#issuecomment-341860410 and https://github.com/NixOS/nixpkgs/pull/67942/. If you want to take up these threads it would be great since the broken user session dbus in NixOS is a constant source of troubles.

**Comment by peterhoeg** [comment]
How about `services.dbus.socketActivated = true;` ?

**Comment by justin-gerhardt** [comment]
It'll be a few days before I can fully dig into implementation @rycee but I'd be happy to contribute. 

> How about `services.dbus.socketActivated = true;` ?

When I said I replaced the xsession dbus with systemd I mean I set
services.xserver.startDbusSession = false;
services.dbus.socketActivated = true;

Dbus is starting fine, the issue is the gnome terminal package can't/doesn't install dbus and systemd services and thus refuses to launch.

**Comment by duog** [comment]
I have what seems to be a solution: add the systemd user units to `$XDG_CONFIG_HOME/systemd/user/` and add the dbus service files to `$XDG_DATA_HOME/dbus-1/services` (as per https://dbus.freedesktop.org/doc/dbus-daemon.1.html)

i.e.
```nix
    xdg.configFile."systemd/user/gnome-terminal-server.service".source = "${pkgs.gnome3.gnome-terminal}/lib/systemd/user/gnome-terminal-server.service";
    xdg.configFile."systemd/user/at-spi-dbus-bus.service".source = "${pkgs.gnome3.gnome-terminal}/lib/systemd/user/at-spi-dbus-bus.service";

    xdg.dataFile."dbus-1/services/org.a11y.Bus.service" = {
      source = "${pkgs.at-spi2-core}/share/dbus-1/services/org.a11y.Bus.service";
      onChange = "systemctl --user reload dbus.service";
    };
```

Is there anything wrong with this approach? It seems home-manager could add `systemd.user.packages` and `dbus.packages` options to autolink the right kinds of files to the right places?

**Comment by rycee** [comment]
Should be fixed in Nixpkgs master now, see https://github.com/NixOS/nixpkgs/pull/97801.

**Comment by piegamesde** [comment]
I still experience the `# Error creating terminal: Unit gnome-terminal-server.service not found.` error. I think this was only resolved on NixOS. `xdg.configFile."systemd/user/gnome-terminal-server.service".source = "${pkgs.gnome.gnome-terminal}/lib/systemd/user/gnome-terminal-server.service";` seems to help but it's not perfect.

**Comment by kkumlien** [comment]
> running `gnome-terminal` works, and `systemctl --user` shows no problems in `gnome-terminal-server`, `at-spi2-dbus-bus` or `dbus.service` Is there anything wrong with this approach? It seems home-manager could add `systemd.user.packages` and `dbus.packages` options to autolink the right kinds of files to the right places?

@duog seems your wish has been granted: #8540
