### ISSUE TITLE
bug: Atuin failing due to bash-preexec

### ISSUE THREAD

**Issue by j0hax** [nix-community/home-manager#2437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When enabling Atuin and Bash in the home-manager options, I get the following error:

```console
error: builder for '/nix/store/i01inyri6rvm5l49q55v5ni21d9aqwjf-bash-preexec-0.4.1.drv' failed with exit code 1;
       last 10 log lines:
       > ok 21 preexec should set $? to be the exit code of preexec_functions
       > ok 22 in_prompt_command should detect if a command is part of PROMPT_COMMAND
       > ok 23 __bp_adjust_histcontrol should remove ignorespace and ignoreboth
       > ok 24 preexec should respect HISTTIMEFORMAT
       > ok 25 preexec should not strip whitespace from commands
       > ok 26 preexec should preserve multi-line strings in commands
       > ok 27 preexec should work on options to 'echo' commands
       > ok 28 should not import if it's already defined
       > ok 29 should import if not defined
       > ok 30 bp should stop installation if HISTTIMEFORMAT is readonly
       For full logs, run 'nix log /nix/store/i01inyri6rvm5l49q55v5ni21d9aqwjf-bash-preexec-0.4.1.drv'.
error: 1 dependencies of derivation '/nix/store/s3x6lzk5ndl6zqp3h3pwdjz2xm69l400-bashrc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4vs86gbgn9v8hsv2qlqhqn9f1pabw7va-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1fcrrmlhgz5izzmhf5kdvjxbci7bz95s-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rnyqkab6k9y8pl1zbg78pz932bzjj2dy-unit-home-manager-johannes.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l2yizrfb9mzzhdag3jbd1kjvyq3djx46-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1za3yxr443ifzl5pxvcw26mxslsdib1j-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/31388jinrcg5128nq7fn67kbzc0jy36a-nixos-system-kirby-21.11.20211101.6d7a521.drv' failed to build
```

It appears the build fails due to test 19:

```
not ok 19 preexec should execute a function with IFS defined to local scope
# (in test file test/bash-preexec.bats, line 260)
#   `[ $status -eq 0 ]' failed
# Error: Test file "/build/source/merge" does not exist
not ok 20 precmd should execute a function with IFS defined to local scope
# (in test file test/bash-preexec.bats, line 269)
#   `[ $status -eq 0 ]' failed
# Error: Test file "/build/source/merge" does not exist
```

### Maintainer CC

@hawkw as module maintainer
@rycee as nixpkgs preexec maintainer

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.14.14-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `"nixos-21.11pre325810.2deb07f3ac4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hawkw** [comment]
Hmm, interesting. It looks like this is the test thati's failing: https://github.com/rcaloras/bash-preexec/blob/da2dbb50efd0999cfd3b1a364ffbb59d77be2d79/test/bash-preexec.bats#L252-L261

But, I'm not sure why off the top of my head --- it looks like the file that's missing is something internal to `bats`?

**Comment by rycee** [comment]
Bisected to https://github.com/NixOS/nixpkgs/commit/b40d30f92d0f887c62e8baea678b059b6732a50a. Will have a look.

**Comment by rycee** [comment]
I simply disabled the problematic tests in the PR above. It is merged now so the build should be fixed in the next Nixpkgs unstable.

**Comment by j0hax** [comment]
Thanks for fixing so quickly.

**Comment by montchr** [comment]
It looks like this issue is back. I've been running into very similar issues with `atuin` and `bash-preexec` since updating `nixos-unstable` to a commit made sometime in the last week-or-so.

Minimal repro:

https://git.sr.ht/~montchr/hm-atuin-failure/tree/main/item/flake.nix

Error:

```console
error: builder for '/nix/store/mbhf127fac9789yis4gjf9rdmrg55rqx-setuptools-44.0.0-sdist.tar.gz.drv'failed with exit code 1;
       last 10 log lines:
       > Traceback (most recent call last):
       >   File "bootstrap.py", line 64, in <module>
       >     __name__ == '__main__' and main()
       >   File "bootstrap.py", line 61, in main
       >     run_egg_info()
       >   File "bootstrap.py", line 54, in run_egg_info
       >     subprocess.check_call(cmd)
       >   File "/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/lib/python2.7/subprocess.py", line 190, in check_call
       >     raise CalledProcessError(retcode, cmd)
       > subprocess.CalledProcessError: Command '['/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/bin/python2.7', u'setup.py', u'egg_info']' returned non-zero exit status 1
       For full logs, run 'nix log /nix/store/mbhf127fac9789yis4gjf9rdmrg55rqx-setuptools-44.0.0-sdist.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/p6pjqvsh094522gpljl0lgfl3y5zsmq2-python2.7-bootstrapped-pip-20.3.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7kp1g21k2lxnks3y0i0zccxrxghyvcbx-python2.7-setuptools-44.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gfvrkw5a0h0f604p7gldnd3knl1h6vgy-python-catch-conflicts-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a73q3cis3fn6rp4mza9fc29nagjji5lm-python2.7-pip-20.3.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/69gv71a1iai34jdcqhminjnvg2db7v9y-setuptools-setup-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ffcl7ab68djwq0zgyy6n2qw85rdb2vdd-resholve-0.8.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/75wyjwc75xijhs52sbxvx86cisxafm9p-bats-1.8.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g2rnc55qplscfjja3k3iwilvi14qspc7-bash-preexec-0.5.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hml6nzn9cpvp4d5qzfhlibjqjspryyp3-bashrc.drv' failedto build
error: 1 dependencies of derivation '/nix/store/himv35x5ad4yr6w8wadmz6lw678m76k4-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dkn5bcfqcivqvghj7phrp8dwwk3dpwps-home-manager-generation.drv' failed to build
```

Log output for failing derivation:

```console
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/vp039y542nr4qq62lxm7d3sd4piix1fi-setuptools-44.0.0-source
source root is setuptools-44.0.0-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/0qzs4kq2lvl09k80nf54bl00hd2ylfam-tag-date.patch
patching file setup.cfg
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
adding minimal entry_points
Regenerating egg_info
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import setuptools
  File "/private/tmp/nix-build-setuptools-44.0.0-sdist.tar.gz.drv-0/setuptools-44.0.0-source/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/private/tmp/nix-build-setuptools-44.0.0-sdist.tar.gz.drv-0/setuptools-44.0.0-source/setuptools/dist.py", line 36, in <module>
    from setuptools import windows_support
  File "/private/tmp/nix-build-setuptools-44.0.0-sdist.tar.gz.drv-0/setuptools-44.0.0-source/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
Traceback (most recent call last):
  File "bootstrap.py", line 64, in <module>
    __name__ == '__main__' and main()
  File "bootstrap.py", line 61, in main
    run_egg_info()
  File "bootstrap.py", line 54, in run_egg_info
    subprocess.check_call(cmd)
  File "/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/bin/python2.7', u'setup.py', u'egg_info']' returned non-zero exit status 1
```
