### ISSUE TITLE
bug:  programs.emacs called without version

### ISSUE THREAD

**Issue by fushiii** [nix-community/home-manager#4436]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

If you try to use `programs.emacs` to install emacs, you will be greeted with a error.

```
error:
       … while calling the 'head' builtin

         at /nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source/lib/attrsets.nix:820:11:

          819|         || pred here (elemAt values 1) (head values) then
          820|           head values
             |           ^
          821|         else

       … while evaluating the attribute 'value'

         at /nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source/lib/modules.nix:800:9:

          799|     in warnDeprecation opt //
          800|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          801|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called without required argument 'version'

       at /nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source/pkgs/build-support/emacs/generic.nix:5:1:

            4|
            5| { pname
             | ^
            6| , version
```

Offending piece of nix:

```
programs.emacs = {
  enable = true;
  extraPackages = epkgs: [
    epkgs.vterm
  ];
};

```

Although if i install it without the module:
`home.packages = with pkgs; [ fd emacs ripgrep ]; `

Everything works fine.

### Maintainer CC

@rycee 

### System information

```markdown
Note: i am using flakes against the unstable version of nixpkgs.
 nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

home-manager.url = "github:nix-community/home-manager";
# Same happens without this
home-manager.inputs.nixpkgs.follows = "nixpkgs";



 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.11 (Tapir), 23.11.20230908.db9208a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source`
```

**Comment by VwCSXg** [comment]
Testing also fails since a nixpkgs update: 
`nix develop --ignore-environment .#all` fails since bfe38782355f2f10bd705c31ff2e71b6471d3f8f with 
```
error: anonymous function at /nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source/pkgs/build-support/emacs/generic.nix:5:1 called without required argument 'version'

       at /nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source/pkgs/build-support/emacs/trivial.nix:9:1:

            8|
            9| callPackage ./generic.nix envargs ({
             | ^
           10|   buildPhase = ''
(use '--show-trace' to show detailed location information)
```

`nix develop --ignore-environment .?rev=edda5599d6bb6e6b7689e7f283c5b12b420dd7da#all` works

**Comment by tadfisher** [comment]
This should have been fixed in https://github.com/nix-community/home-manager/pull/4420; try updating your flake.

**Comment by fushiii** [comment]
> This should have been fixed in #4420; try updating your flake.

Updating the inputs did fix the issue. Sorry for opening a issue in the wrong place.

**Comment by what-the-functor** [comment]
I've updated the flake inputs, and I still see this error.  Is this fixed for nixpkgs-23.11?

Flake inputs
```nix
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-23.11-darwin";
    home-manager = {
      url = "github:nix-community/home-manager/19c6a40";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-utils.url = "github:numtide/flake-utils";
  };
```

Emacs configuration
```nix
  programs.emacs = {
    enable = true;
    package = pkgs.emacs;
    extraPackages = ...

    extraConfig = builtins.readFile ./emacs/init.el;
  };
```

```bash
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/i7n88i27y58ri8gibx1gqx3qm6v5simy-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'

         at /nix/store/i7n88i27y58ri8gibx1gqx3qm6v5simy-source/pkgs/build-support/trivial-builders/default.nix:87:14:

           86|       enableParallelBuilding = true;
           87|       inherit buildCommand name;
             |              ^
           88|       passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called without required argument 'version'

       at /nix/store/i7n88i27y58ri8gibx1gqx3qm6v5simy-source/pkgs/build-support/emacs/generic.nix:25:1:

           24|
           25| { pname
             | ^
           26| , version
```

**Comment by tadfisher** [comment]
@what-the-functor That fix is in release-23.11. I don't know what you're pinning to with

```
github:nix-community/home-manager/19c6a40
```

But try changing that hash to `release-23.11`.

**Comment by what-the-functor** [comment]
@tadfisher `19c6a40` is the commit that closes #4420.  The same error occurs with `release-23.11`

**Comment by what-the-functor** [comment]
I fixed my flake.  I'm using `epkgs.trivialBuild`, which now requires `version`.
