### ISSUE TITLE
bug: module podman

### ISSUE THREAD

**Issue by Nosirus** [nix-community/home-manager#6146]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When I try the podman module, at startup nothing starts and I find this error in the service logs.

But if I start it manually with systemctl --user start podman-epicgame.service it works

`nov. 28 13:26:09 cobblepot systemd[2034]: Starting Service for container gotify...
nov. 28 13:26:09 cobblepot podman[3347]: 2024-11-28 13:26:09.530256926 +0100 CET m=+0.041632954 container create d4cb699cc558de2562921803192f015201913d13e65953114150ee965207b4c9 (image=docker.io/gotify/ser>
nov. 28 13:26:09 cobblepot pasta[3472]: External interface not usable
nov. 28 13:26:09 cobblepot podman[3347]: 2024-11-28 13:26:09.554409169 +0100 CET m=+0.065785217 container remove d4cb699cc558de2562921803192f015201913d13e65953114150ee965207b4c9 (image=docker.io/gotify/ser>
nov. 28 13:26:09 cobblepot podman-gotify[3347]: Error: setting up Pasta: pasta failed with exit code 1:
nov. 28 13:26:09 cobblepot podman-gotify[3347]: External interface not usable`

### System information

```markdown
[nosirus@cobblepot:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.1, NixOS, 25.05 (Warbler), 25.05.20241125.4633a7c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/frfyxcpzsdasdin76x83krbhpgkis8b0-source`
```

**Comment by Nosirus** [comment]
I found the cause, the service "podman-user-wait-network-online" could not find "sh" so I redid the service like this:

```
systemd.user.services.podman-user-wait-network-online = {
  Unit = { Description = "Wait for system level network-online.target as user"; };
  Service = {
    Type = "oneshot";
    ExecStart = "${pkgs.bash}/bin/sh -c 'until systemctl is-active network-online.target; do sleep 0.5; done'";
    TimeoutStartSec = "90s";
    RemainAfterExit = true;
  };
  Install = { WantedBy = [ "default.target" ]; };
};
```

**Comment by n-hass** [comment]
Fixed by #6150

**Comment by bamhm182** [comment]
As n-hass had said, that commit should have resolved the issue. Are you still having issues with this @Nosirus or can it be closed?

**Comment by Tarow** [comment]
The commit fixed the `sh` issue for me, however `sleep` was still not in the PATH so the service still failed which causes the podman containers not to come up correctly on reboot:
```
❯ journalctl --user -fu podman-user-wait-network-online.service
Feb 26 07:36:40 nixos sh[6563]: inactive
Feb 26 07:36:40 nixos sh[6564]: sh: line 1: sleep: command not found
Feb 26 07:36:40 nixos sh[6565]: inactive
Feb 26 07:36:40 nixos sh[6566]: sh: line 1: sleep: command not found
Feb 26 07:36:40 nixos sh[6567]: inactive
Feb 26 07:36:40 nixos sh[6571]: sh: line 1: sleep: command not found
Feb 26 07:36:41 nixos systemd[1277]: podman-user-wait-network-online.service: Main process exited, code=exited, status=127/n/a
Feb 26 07:36:41 nixos systemd[1277]: podman-user-wait-network-online.service: Failed with result 'exit-code'.
Feb 26 07:36:41 nixos systemd[1277]: Failed to start Wait for system level network-online.target as user..
Feb 26 07:36:41 nixos systemd[1277]: podman-user-wait-network-online.service: Consumed 5.619s CPU time, 4.4M memory peak.
```

Also adding `coreutils` to the PATH fixed it for me:
```nix
xdg.configFile."systemd/user/podman-user-wait-network-online.service.d/50-exec-search-path.conf".text = ''
  [Service]
  ExecSearchPath=${lib.makeBinPath (with pkgs; [bashInteractive systemd coreutils])}:/bin
'';
```
