### ISSUE TITLE
Feature Request: pay-respects

### ISSUE THREAD

**Issue by muItilingualism** [nix-community/home-manager#6204]
### Description
> `pay-respects`, a terminal command correction program, alternative to `thefuck`, written in Rust. Available as programs.pay-respects.

Hi, `pay-respects` was added in NixOS 24.11, and I'd like it to be in home-manager as well, since `thefuck` does not seem to be maintained.

Relevant links:
- [`pay-respects` repo](https://codeberg.org/iff/pay-respects)
- [nixpkgs pay-respects request](https://github.com/NixOS/nixpkgs/issues/355631)
- [nixpkgs pay-respects PR](https://github.com/NixOS/nixpkgs/pull/355694)
- [24.11 release notes mentioning `pay-respects`](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md)

Thanks!

**Comment by Adda0** [comment]
We should also add an option to specify the [suggestion rules](https://github.com/iffse/pay-respects/blob/main/rules.md), written in Nix and converted to TOML files which get inserted at the required location (`~/.config/pay-respects/rules/<command_name>.toml`), e.g.:
```nix
programs.pay-respects.rules = {
  cargo = {
    # Rule file `cargo.toml` for `cargo` command.
  };
  make = {
    # Rule file `make.toml` for `make` command.
  };
  # ...
}
```

**Comment by SimonYde** [comment]
currently the module does not work for nushell, as there is the placeholder "[<alias>]" which should be an alias like the default "f".

**Comment by SimonYde** [comment]
Perhaps an HM option should be added to change the alias used

**Comment by jpteb** [comment]
The config option for nushell fundamentally doesn’t work with nixos. This is because the `pay-respects nushell` command attempts to manually write its alias to the configuration file, which doesn't work, as it is read-only.

Additionally, I haven’t been able to get the command to work properly at all. I’ve tried various arguments with `pay-respects nushell --alias ...`, but none of them worked as expected. But this doesn't really matter, as my solution writes the command by itself.

I'll create a pr shortly, but the nushell integration is a bit scuffed, as it relies on internal code and breaks as soon as the nushell integration doesn't print the command in the first line anymore.

**Comment by ALameLlama** [comment]
> We should also add an option to specify the [suggestion rules](https://github.com/iffse/pay-respects/blob/main/rules.md?rgh-link-date=2024-12-22T11%3A34%3A25Z), written in Nix and converted to TOML files which get inserted at the required location (`~/.config/pay-respects/rules/<command_name>.toml`), e.g.:
> 
> ```nix
> programs.pay-respects.rules = {
>   cargo = {
>     # Rule file `cargo.toml` for `cargo` command.
>   };
>   make = {
>     # Rule file `make.toml` for `make` command.
>   };
>   # ...
> }
> ```

I'm not sure this will work since the rules must be recompiled and don't hot load them in.

**Comment by iffse** [comment]
> I'm not sure this will work since the rules must be recompiled and don't hot load them in.

@ALameLlama For versions `0.5.x`, rules can be read at runtime with `runtime-rules` feature. For versions `>=0.6`, runtime rules support is provided by `runtime-rules` module. Older versions only support compile-time rules.

**Comment by ALameLlama** [comment]
> > I'm not sure this will work since the rules must be recompiled and don't hot load them in.
> 
> @ALameLlama For versions `>=0.6`, runtime rules support is provided by `runtime-rules` module. For versions `0.5.x`, rules can be read at runtime with `runtime-rules` feature. Older versions only support compile-time rules.

That's awesome, I hope people still end up upstreaming changes instead of keeping it to themselves

**Comment by zliuva** [comment]
> We should also add an option to specify the [suggestion rules](https://github.com/iffse/pay-respects/blob/main/rules.md), written in Nix and converted to TOML files which get inserted at the required location (`~/.config/pay-respects/rules/<command_name>.toml`), e.g.:
> 
> programs.pay-respects.rules = {
>   cargo = {
>     # Rule file `cargo.toml` for `cargo` command.
>   };
>   make = {
>     # Rule file `make.toml` for `make` command.
>   };
>   # ...
> }

I have the same need and ended up doing something like this:

```nix
{
  config,
  pkgs,
  ...
}: let
  pay-respects = pkgs.pay-respects.overrideAttrs (oldAttrs: {
    cargoBuildFlags =
      oldAttrs.cargoBuildFlags or []
      ++ [
        "-p"
        "pay-respects"
        "-p"
        "pay-respects-module-runtime-rules"
      ];
  });
in {
  programs.pay-respects = {
    enable = true;
    package = pay-respects;
  };

  home.file."${config.xdg.configHome}/pay-respects/rules/git.toml" = {
    text = ''
      command = "git"

      [[match_err]]
      pattern = [
        "..."
      ]

      suggest = [
        "... && {{command}}"
      ]
    '';
  };
}
```

dropping in the rules are easy with `home.file` but it took me quite a while to realize I had to override the upstream package to build with the runtime-rules module.

**Comment by taranarmo** [comment]
I guess this was fixed with https://github.com/nix-community/home-manager/pull/6210

**Comment by Adda0** [comment]
The only thing missing in #6210 is allowing to set rules for pay-respects. I am not sure what is the state of pay-respects upstream development, but AFAIK, it is still not possible to configure those as shown above without recompiling. We could create a new issue while someone investigates what could be done about the rules in home manager.

**Comment by RafaelKr** [comment]
> The only thing missing in [#6210](https://github.com/nix-community/home-manager/pull/6210) is allowing to set rules for pay-respects. I am not sure what is the state of pay-respects upstream development, but AFAIK, it is still not possible to configure those as shown above without recompiling. We could create a new issue while someone investigates what could be done about the rules in home manager.

Using the `home.file."${config.xdg.configHome}/pay-respects/rules/git.toml"` shown above should work, see runtime-rules at https://github.com/iffse/pay-respects/blob/main/rules.md#writing-rules

**Comment by Adda0** [comment]
Yeah. It should work, but you need to manually override the package and use `home.file`. It is not integrated to the module itself, which is a bit of a shame. I wanted to see whether this all could be abstracted away by using a submodule option in the pay-respects module.

**Comment by taranarmo** [comment]
I also noticed that enabling the module without installing either of `nix-search-cli` or `nix-index` explicitly will break command-not-found-like functionality, as pay-respects will complain that it couldn't find those. Should it be raised as a separate issue?

**Comment by Adda0** [comment]
I agree that these are two separate issues. I would recommend creating a new issue which would ask for a new option setting the default provider of the search functionality, with the ability to reconfigure it. Maybe Something like `enableNixSearchCliIntegration = config.programs.nix-search-cli.enable` and `enableNixIndexIntegration` = config.programs.nix-index.enable`, and maybe disable one of them by default. Are these two options mutually exclusive? Or just one option which selects the provider and enables it...
