### ISSUE TITLE
udiskie: Can't find file browser: 'xdg-open'.

### ISSUE THREAD

**Issue by pmiddend** [nix-community/home-manager#632]
I don't think this is a huge problem, but while looking at `systemctl --user status udiskie`, I saw this in the log:

```
udiskie[1703]: Can't find file browser: 'xdg-open'. You may want to change the value for the '-f' option.
```

**Comment by rycee** [comment]
I'm thinking this ideally should be fixed in the Nixpkgs package by either substituting `xdg-open` in the udiskie source or wrapping the executables so that xdg-open is in PATH.

**Comment by imoBooze** [comment]
I've also been encountering this issue.  I've attempted to set the mimetypes so that "inode/directory" will always use my file browser, but the problem still remains.

**Comment by h0m1** [comment]
Same problem here. As a workaround, you can explicitly set the file manager in the settings. That works for me.
```
udiskie = {
  enable = true;
  automount = false;
  settings = {
    program_options = {
      # file_manager = "${pkgs.xdg-utils}/bin/xdg-open";
      file_manager = "${pkgs.alacritty}/bin/alacritty -e ${pkgs.yazi}/bin/yazi";
    };
  };
};
```

**Comment by mobsenpai** [comment]
Why is this marked as completed?
