### ISSUE TITLE
bug: `television` shell integration broken

### ISSUE THREAD

**Issue by starcraft66** [nix-community/home-manager#8400]
### Are you following the right branch?

- [x] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Issue description

The nixpkgs package [changed how completions are stored](https://github.com/NixOS/nixpkgs/commit/02ff23113ad96329fab23a3deef266c225d9a7f1) and the format seems to have changed:

```
/nix/store/yir2cij3v6yhc4ajyrplgsxwpm6zd74b-television-0.14.1/
├── bin/
│   └── tv*
└── share/
    ├── bash-completion/
    │   └── completions/
    │       └── tv.bash
    ├── fish/
    │   └── vendor_completions.d/
    │       └── tv.fish
    ├── man/
    │   └── man1/
    │       └── tv.1.gz
    ├── nushell/
    │   └── vendor/
    │       └── autoload/
    │           └── tv.nu
    └── zsh/
        └── site-functions/
            └── _tv
```

I see in my shell: `/home/tristan/.config/zsh/.zshrc:source:899: no such file or directory: /nix/store/yir2cij3v6yhc4ajyrplgsxwpm6zd74b-television-0.14.1/share/television/completion.zsh`

### System information

```markdown
@luna:~ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.2, NixOS, 26.05 (Yarara), 26.05.20251221.a653104`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.31.2+1`
 - channels(root): `""`
 - channels(tristan): `""`
 - nixpkgs: `/nix/store/bqqk8vbs25c99wvxiib1jdmba3ppm7lv-1ny7brxnqbx6xilj7mjdlinzpb5a1s3i-source`
```

**Comment by khaneliman** [comment]
Should be resolved after latest flake bump

**Comment by daniel-hernandez-sony** [comment]
Unfortunately, I am still getting this with home-manager  `8bc5473b6bc2b6e1529a9c4040411e1199c43b4c`. @starcraft66 ,  was your issue  resolved?

**Comment by starcraft66** [comment]
Yup seems fixed thanks.
